<?php

return [
    'devotions' => ['Not Religious', 'Slightly Religious',
        'Moderately Religious', 'Religious', 'Very Religious', 'Prefer Not to Say'],
    'ar_devotions' => ['غير متدين', 'متدين قليلاً', 'متدين بدرجة متوسطة', 'متدين', 'متدين جداً', 'لا أريد الإجابة'],
    'genders' => ['Male', 'Female', 'Prefer Not to Say'],
    'ar_genders' => ['ذكر', 'أنثى', 'لا أريد الإجابة'],
    'prayer_commitments' => ['Pray all 5 daily prayers regularly', 'Pray most prayers (sometimes miss)',
        'Pray occasionally', 'Trying to be more consistent', 'Prefer not to say',
    ],
    'ar_prayer_commitments' => ['أصلي الصلوات الخمس بانتظام', 'أصلي أغلب الصلوات', 'أصلي أحيانًا',
        'أحاول الالتزام بالصلاة', 'أفضل عدم الإجابة'],
    'yes_no_list' => ['Yes', 'No', 'Prefer not to say'],
    'ar_yes_no_list' => ['نعم', 'لا', 'لا أريد الإجابة'],
    'education_levels' => ['High School', 'Diploma', 'Bachelor’s Degree', 'Master’s Degree',
        'Doctorate (PhD)', 'Currently Studying', 'Prefer not to say', ],
    'ar_education_levels' => ['الثانوية العامة', 'دبلوم', 'بكالوريوس', 'ماجستير', 'دكتوراه', 'طالب', 'أفضل عدم الإجابة'],
    'financial_statuses' => ['Financially stable', 'Comfortable', 'Average', 'Improving / Building stability',
        'Limited income', 'Prefer not to say'],
    'ar_financial_statuses' => ['مستقر ماديًا', 'مرتاح ماديًا', 'متوسط', 'في طور تحسين وضعي المادي', 'دخل محدود', 'أفضل عدم الإجابة'],
    'fields_of_work' => ['Information Technology', 'Engineering', 'Healthcare / Medical',
        'Education / Teaching', 'Business / Management', 'Finance / Accounting',
        'Sales / Marketing', 'Government / Public Sector', 'Law / Legal Services',
        'Construction / Real Estate', 'Manufacturing / Industry', 'Transportation / Logistics',
        'Hospitality / Tourism', 'Media / Design / Creative', 'Retail / Customer Service', 'Agriculture / Food',
        'Self-Employed / Freelance', 'Not Working Currently',
    ],
    'ar_fields_of_work' => ['تكنولوجيا المعلومات', 'الهندسة', 'القطاع الصحي / الطبي', 'التعليم / التدريس',
        'الأعمال / الإدارة', 'المالية / المحاسبة', 'المبيعات / التسويق', 'القطاع الحكومي',
        'القانون / الخدمات القانونية', 'المقاولات / العقارات', 'الصناعة', 'النقل / الخدمات اللوجستية',
        'الضيافة / السياحة', 'الإعلام / التصميم / الإبداع', 'البيع بالتجزئة / خدمة العملاء', 'الزراعة / الغذاء',
        'عمل حر', 'لا أعمل حاليا'],

];
